server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/redoc"
  serverRoot: "/resource/public"


logger:
  level: "all"
  stdout: true
gfToken:
  cacheKey: "gf_t_"
  timeOut: 10800
  maxRefresh: 5400
  multiLogin: true
  encryptKey: "49c54195e750b04e74a8429b17896586"
  cacheModel: "redis"
  excludePaths:
    - "/api/v1/hello/*"
    - "/api/v1/system/xxx2"

# Database.
database:
  logger:
    level: "all"
    stdout: true
    Path: "resource/log/sql"
  default:
    link: "mysql:root:123456@tcp(localhost:3306)/demo"
    debug: true
    charset: "utf8mb4" #数据库编码
    dryRun: false #空跑
    maxIdle: 10 #连接池最大闲置的连接数
    maxOpen: 10 #连接池最大打开的连接数
    maxLifetime: 30 #(单位秒)连接对象可重复使用的时间长度

# Redis 配置示例
redis:
  # 单实例配置
  default:
    address: 127.0.0.1:6379
    db: 1
    idleTimeout: 600
    maxActive: 100

