// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id          uint64      `json:"id"          description:"用户ID"`
	UserName    string      `json:"userName"    description:"姓名"`
	Age         int         `json:"age"         description:"年龄"`
	Sex         int         `json:"sex"         description:"性别（1男 2女 0未知）"`
	PhoneNumber string      `json:"phoneNumber" description:"手机号码"`
	CompanyId   string      `json:"companyId"   description:"单位id"`
	CompanyName string      `json:"companyName" description:"单位"`
	Status      int         `json:"status"      description:"帐号状态（0正常 1停用）"`
	OpenId      string      `json:"openId"      description:"来源账号id"`
	Avatar      string      `json:"avatar"      description:"图像路径"`
	SysUserId   uint64      `json:"sysUserId"   description:"中台用户ID"`
	SysPersonId uint64      `json:"sysPersonId" description:"中台人员ID"`
	AdminFlag   int         `json:"adminFlag"   description:"管理员标志，0否，1是"`
	DelFlag     int         `json:"delFlag"     description:"删除标志（0代表存在 1代表删除）"`
	CreateBy    string      `json:"createBy"    description:"创建者"`
	CreateTime  *gtime.Time `json:"createTime"  description:"创建时间"`
	UpdateBy    string      `json:"updateBy"    description:"更新者"`
	UpdateTime  *gtime.Time `json:"updateTime"  description:"更新时间"`
}
